#! /bin/sh

## autostart ##

# keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# compositor
pgrep -x picom > /dev/null || picom &

# notifications
pgrep -x dunst > /dev/null || dunst &

# wallpaper # order acording to `xrandr --listmonitors`
feh --no-fehbg --bg-fill /home/d/Pictures/dual_1440p/cuts/6593144_right.jpg /home/d/Pictures/dual_1440p/cuts/6593144_left.jpg || echo "Check wallpaper path?"

# status bar
polybar BAR0 &
polybar BAR1 &


## bspwm config ##
bspc monitor DisplayPort-2 -d I II III IV &
bspc monitor DisplayPort-1 -d V VI VII VIII &


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'

## other uses
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
