#! /bin/sh

## load some auxillary things first

# keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# compositor
picom &

# wallpaper
feh --no-fehbg --bg-fill ~/Pictures/nature/nature-3082832.jpg

# status bar
polybar &

## bspwm config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
