#! /bin/sh

## load some auxillary things first ##

# keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# compositor
picom &

# notifications
dunst &

# wallpaper # order acording to `xrandr --listmonitors`
feh --no-fehbg --bg-fill $HOME/Pictures/dual_1440p/cuts/6593144_right.jpg \
                         $HOME/Pictures/dual_1440p/cuts/6593144_left.jpg

# status bar
polybar main &
polybar secondary & # second monitor

## bspwm config ##

## single monitor
#bspc monitor -d I II III IV V VI VII VIII IX X

## multi monitor
bspc monitor DisplayPort-2 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'

## other uses
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
