# author = "Chris Kempson"
# name = "Atelierseaside (dark)"

[colors.bright]
black = "#687d68"
blue = "#3d62f5"
cyan = "#1999b3"
green = "#29a329"
magenta = "#ad2bee"
red = "#e6193c"
white = "#f0fff0"
yellow = "#c3c322"

[colors.cursor]
cursor = "#8ca68c"
text = "#131513"

[colors.normal]
black = "#131513"
blue = "#3d62f5"
cyan = "#1999b3"
green = "#29a329"
magenta = "#ad2bee"
red = "#e6193c"
white = "#8ca68c"
yellow = "#c3c322"

[colors.primary]
background = "#131513"
foreground = "#8ca68c"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 11

[font.normal]
family = "$GLOBAL_FONT"
style = "Regular"

[window]
opacity = 0.8
