#! /bin/sh

# required for programs like dolphin to be styled correctly
export QT_QPA_PLATFORMTHEME=qt5ct

## autostart ##

# keybinds
pgrep -x sxhkd >/dev/null || sxhkd &

# compositor
pgrep -x picom >/dev/null || picom &

# notifications
pgrep -x dunst >/dev/null || dunst &

/usr/lib/polkit-kde-authentication-agent-1 &

bash $SCRIPTS/check_updates.sh &

$EXTRA_AUTOSTART

# wallpaper # order acording to `xrandr --listmonitors`
feh --no-fehbg --bg-fill $WALLPAPERS || echo "Check wallpaper path?"

# status bar
$BARSENABLE

## bspwm config ##
$BSPCMON

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Firefox desktop='^2'
bspc rule -a "matplotlib" state=floating
bspc rule -a "Zathura" state=tiled

bspc monitor -f "^1"
bspc desktop -f "^1"
xdotool mousemove 100 100

## other uses
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
